name: zego_uikit_beauty_plugin
description: ZegoUIKitBeautyPlugin is a low-code beauty collection, which helps you to integarte features easier and faster.
version: 1.7.11
homepage: https://www.zegocloud.com/

environment:
  sdk: ">=2.16.2 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  
  zego_effects_plugin: ^1.0.14
  zego_plugin_adapter: ^2.13.11
  shared_preferences: ^2.2.2
  path_provider_android: ^2.2.0
  
  flutter_logs_yoer: ^2.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  lints: ^6.0.0

  import_sorter: ^4.6.0 # run 'flutter pub run import_sorter:main'

flutter:
  plugin:
    platforms:
      android:
        package: com.zegocloud.zego_uikit_beauty_plugin
        pluginClass: ZegoUIKitBeautyPlugin
      ios:
        pluginClass: ZegoUIKitBeautyPlugin
  assets:
    - assets/icons/
    - assets/icons/background/
    - assets/icons/effect/
    - assets/icons/filter/dreamy/
    - assets/icons/filter/gray/
    - assets/icons/filter/nature/
    - assets/icons/beauty/makeup/
    - assets/icons/beauty/makeup/blush/
    - assets/icons/beauty/makeup/eyelash/
    - assets/icons/beauty/makeup/eyeline/
    - assets/icons/beauty/makeup/eyeshadow/
    - assets/icons/beauty/makeup/lipstick/
    - assets/icons/beauty/makeup/coloredcontacts/
    - assets/icons/beauty/shape/
    - assets/icons/beauty/skin/
    - assets/icons/beauty/style_makeup/

linter:
  rules:
    public_member_api_docs: true
